future: true
permalink: /post/:title

title: "HP Template"
desc: "홈페이지 템플릿 연습"
url: "https://example.com"

base_color: "#333333"

menus:
- "About": ["Our People|#", "Company|#"]
- "Business": ["Biz 1|#", "Biz 2|#", "Biz 3|#", "Biz 4|#"]
- "Brand": ["Brand 1|#"]
- "Location": ["Office|#", "Factory|#"]
- "Contact Us": ["Call Us|#"]
