future: true
permalink: /post/:title

title: "HP Template"
desc: "홈페이지 템플릿 연습"
url: "https://example.com"

base_color: "#333333"
header_color: "#eeeeee"

menus:
- title: "About"
  subs: ["Our People", "Company"]
  urls: ["#", "#"]
- title: "Business"
  subs: ["Biz 1", "Biz 2", "Biz 3", "Biz 4"]
  urls: ["#", "#", "#", "#"]
- title: "Location"
  subs: ["Office", "Factory"]
  urls: ["#", "#"]
- title: "Brand"
  subs: ["Brand 1"]
  urls: ["#"]
- title: "Contact Us"
  subs: ["E-mail"]
  urls: ["#"]
